#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
dunst &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2'
bspc rule -a Steam desktop='^5' state=floating rectangle=1376x625+0+0 follow=off
